test

diff --git a/.github/workflows/ci_main.yml b/.github/workflows/ci_main.yml
--- a/.github/workflows/ci_main.yml
+++ b/.github/workflows/ci_main.yml
@@ -18,7 +18,7 @@ concurrency:
 
 jobs:
   vars:
-    if: github.event.pull_request.draft == false
+    if: github.event.pull_request.draft == false && github.event.action != 'closed' && github.event_name == 'pull_request'
     name: Initialize variables
     runs-on: ubuntu-latest
     steps:
@@ -49,7 +49,7 @@ jobs:
 
   ci:
     name: Run CI
-    if: github.event.action != 'closed' && github.event_name == 'pull_request' && needs.vars.outputs.changed != '[]'
+    if: success() && needs.vars.outputs.changed != '[]'
     needs:
       - vars
     runs-on: ubuntu-latest
@@ -69,15 +69,17 @@ jobs:
           export LC_ALL=C
           source '.github/workflows/ci_${{ matrix.package }}.sh'
     
-  complete:
-    name: complete
-    if: success()
-    runs-on: ubuntu-latest
-    needs:
-      - ci
-    steps:
-      - id: fail
-        run: exit 0
+  # complete:
+  #   name: complete
+  #   if: success()
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - ci
+  #   steps:
+  #     - id: fail
+  #       run: exit 1
+
+  #       echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
 
     
   tag:
